language: generic
sudo: required
services: 
  - docker

before_install: 
  - docker build -t manaspati/react-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run -e CI=true manaspati/react-test npm test

after_success:
  - docker build -t manaspati/multi-client ./client
  - docker build -t manaspati/multi-nginx ./nginx
  - docker build -t manaspati/multi-server ./server
  - docker build -t manaspati/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push manaspati/multi-client
  - docker push manaspati/multi-nginx
  - docker push manaspati/multi-server
  - docker push manaspati/multi-worker
